name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Full version (e.g., 1.0.0, 2.3.5, etc.)"
        required: true
        default: "1.0.0"
        type: string
      pre_release:
        description: "Pre-release tag (e.g., beta.1)"
        required: false
        type: string

env:
  IMAGE_NAME: hyporia123/telegram-bot-mcp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for efficient layers caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # Always tag as latest
            type=raw,value=latest
            # Full version from input
            type=raw,value=${{ inputs.version }}${{ inputs.pre_release != '' && format('-{0}', inputs.pre_release) || '' }}
            # Git SHA for precise tracking
            type=sha,format=short

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Telegram.Bot.MCP.Infra.Host/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
